export const blockNO = [
  {
    width: 48,
    height: 29,
    depth: 16,
    finish: { color: 'RED', customColor: null, shelves: false },
    options: { shelfLiner: false },
    frame: {
      width: 48,
      height: 24,
      depth: 16,
      finish: { color: 'Clear Anodized', openingColor: 'Clear Anodized' },
      bottomRail: true,
      gasketLoc: null,
    },
    shell: {
      backPanel: false,
      topPanel: true,
      bottomPanel: true,
      toekick: null,
      internalBracing: { left: false, right: false },
    },
    extensions: { left: null, right: { type: 'joined', width: 0 } },
    soffit: { height: 3, left: false, right: false, front: true },
    radius: {
      left: false,
      right: false,
      top: false,
      bottom: true,
      lighting: {
        switches: 'none',
        wiring: 'left',
        lights: 0,
        voltage: null,
        lightType: 'none',
      },
    },
    openings: [
      {
        frame: {
          left: 'end rail',
          right: 'end rail',
          top: 'top rail',
          bottom: 'bottom rail',
          finish: { color: 'Clear Anodized' },
        },
        width: 45,
        height: 21,
        depth: 16,
        openings: [
          {
            frame: {
              left: 'end rail',
              right: 'center rail',
              top: 'top rail',
              bottom: 'bottom rail',
              finish: { color: 'Clear Anodized' },
            },
            width: 14,
            height: 21,
            depth: 16,
            contents: {
              type: 'door',
              data: {
                width: 13.75,
                height: 20.5,
                finish: { color: 'RED' },
                handle: {
                  type: 'MotionLatch',
                  swing: 'left',
                  locking: false,
                  finish: { color: 'Clear Anodized' },
                },
                support: 'none',
                steel: false,
                venting: {
                  top: { height: 0, offset: 0 },
                  bottom: { height: 0, offset: 0 },
                },
              },
              shelves: {
                adjustable: 0,
                slideOut: 0,
                hangerBar: 0,
                liner: false,
              },
            },
          },
          {
            frame: {
              left: 'center rail',
              right: 'center rail',
              top: 'top rail',
              bottom: 'bottom rail',
              finish: { color: 'Clear Anodized' },
            },
            width: 14,
            height: 21,
            depth: 16,
            contents: {
              type: 'door',
              data: {
                width: 13.75,
                height: 20.5,
                finish: { color: 'RED' },
                handle: {
                  type: 'MotionLatch',
                  swing: 'left',
                  locking: false,
                  finish: { color: 'Clear Anodized' },
                },
                support: 'none',
                steel: false,
                venting: {
                  top: { height: 0, offset: 0 },
                  bottom: { height: 0, offset: 0 },
                },
              },
              shelves: {
                adjustable: 0,
                slideOut: 0,
                hangerBar: 0,
                liner: false,
              },
            },
          },
          {
            frame: {
              left: 'center rail',
              right: 'end rail',
              top: 'top rail',
              bottom: 'bottom rail',
              finish: { color: 'Clear Anodized' },
            },
            width: 14,
            height: 21,
            depth: 16,
            contents: {
              type: 'door',
              data: {
                width: 13.75,
                height: 20.5,
                finish: { color: 'RED' },
                handle: {
                  type: 'MotionLatch',
                  swing: 'right',
                  locking: false,
                  finish: { color: 'Clear Anodized' },
                },
                support: 'none',
                steel: false,
                venting: {
                  top: { height: 0, offset: 0 },
                  bottom: { height: 0, offset: 0 },
                },
              },
              shelves: {
                adjustable: 0,
                slideOut: 0,
                hangerBar: 0,
                liner: false,
              },
            },
          },
        ],
      },
    ],
  },
  {
    width: 50,
    height: 29,
    depth: 16,
    finish: { color: 'RED', customColor: null, shelves: false },
    options: { shelfLiner: false },
    frame: {
      width: 50,
      height: 24,
      depth: 16,
      finish: { color: 'Clear Anodized', openingColor: 'Clear Anodized' },
      bottomRail: true,
      gasketLoc: null,
    },
    shell: {
      backPanel: true,
      topPanel: true,
      bottomPanel: true,
      toekick: null,
      internalBracing: { left: false, right: false },
    },
    extensions: { left: { type: 'joined', width: 0 }, right: null },
    soffit: { height: 3, left: false, right: false, front: true },
    radius: {
      left: false,
      right: false,
      top: false,
      bottom: true,
      lighting: {
        switches: 'none',
        wiring: 'left',
        lights: 0,
        voltage: null,
        lightType: 'none',
      },
    },
    openings: [
      {
        frame: {
          left: 'end rail',
          right: 'end rail',
          top: 'top rail',
          bottom: 'bottom rail',
          finish: { color: 'Clear Anodized' },
        },
        width: 47,
        height: 21,
        depth: 16,
        openings: [
          {
            frame: {
              left: 'end rail',
              right: 'center rail',
              top: 'top rail',
              bottom: 'bottom rail',
              finish: { color: 'Clear Anodized' },
            },
            width: 22.75,
            height: 21,
            depth: 16,
            contents: {
              type: 'door',
              data: {
                width: 22.5,
                height: 20.5,
                finish: { color: 'RED' },
                handle: {
                  type: 'MotionLatch',
                  swing: 'left',
                  locking: false,
                  finish: { color: 'Clear Anodized' },
                },
                support: 'none',
                steel: false,
                venting: {
                  top: { height: 0, offset: 0 },
                  bottom: { height: 0, offset: 0 },
                },
              },
              shelves: {
                adjustable: 0,
                slideOut: 0,
                hangerBar: 0,
                liner: false,
              },
            },
          },
          {
            frame: {
              left: 'center rail',
              right: 'end rail',
              top: 'top rail',
              bottom: 'bottom rail',
              finish: { color: 'Clear Anodized' },
            },
            width: 22.75,
            height: 21,
            depth: 16,
            contents: {
              type: 'door',
              data: {
                width: 22.5,
                height: 20.5,
                finish: { color: 'RED' },
                handle: {
                  type: 'MotionLatch',
                  swing: 'right',
                  locking: false,
                  finish: { color: 'Clear Anodized' },
                },
                support: 'none',
                steel: false,
                venting: {
                  top: { height: 0, offset: 0 },
                  bottom: { height: 0, offset: 0 },
                },
              },
              shelves: {
                adjustable: 0,
                slideOut: 0,
                hangerBar: 0,
                liner: false,
              },
            },
          },
        ],
      },
    ],
  },
];
